# Generated by Django 3.1.2 on 2020-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_about',
            field=models.IntegerField(choices=[('補足', '補足'), (2, '意見'), (3, 'その他')]),
        ),
    ]
