# Generated by Django 3.1.2 on 2020-10-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_sharing_app', '0002_auto_20201029_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_about',
            field=models.IntegerField(choices=[(1, '補足'), (2, '意見'), (3, 'その他')]),
        ),
    ]
